POST /api/v1/addArticle HTTP/1.1
Host: 127.0.0.1:8001
Content-Type: application/json
Content-Length: 518

{
  "tag_id": 5,
  "tag":{
  },
  "title": "坚持严的主基调不动摇 坚持不懈把全面从严治党向纵深推进",
  "desc": "坚持严的主基调不动摇 坚持不懈把全面从严治党向纵深推进1",
  "content": "一百年来，党外靠发展人民民主、接受人民监督，内靠全面从严治党、推进自我革命，勇于坚持真理、修正错误，勇于刀刃向内、刮骨疗毒，保证了党长盛不衰、不断发展壮大。全面从严治党是新时代党的自我革命的伟大实践，开辟了百年大党自我革命的新境界。必须坚持以党的政治建设为统领，坚守自我革命根本政治方向；必须坚持把思想建设作为党的基础性建设，淬炼自我革命锐利思想武器；必须坚决落实中央八项规定精神、以严明纪律整饬作风，丰富自我革命有效途径；必须坚持以雷霆之势反腐惩恶，打好自我革命攻坚战、持久战；必须坚持增强党组织政治功能和组织力凝聚力，锻造敢于善于斗争、勇于自我革命的干部队伍；必须坚持构建自我净化、自我完善、自我革新、自我提高的制度规范体系，为推进伟大自我革命提供制度保障。",
  "created_by": "vino",
  "modified_by":"vino",
  "state": 1
}