GET /api/v1/tags?page=1 HTTP/1.1
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJwYXNzd29yZCI6InRlc3QxMjM0NTYiLCJleHAiOjE2NzkyNTE0MDksImlzcyI6InZpbm80Mi1naW4tYmxvZyJ9.avRF_Lfk0Dgih8B0KhGF013dV98LI59jcdrzm7Di8pk
Host: 127.0.0.1:8001